-- Data is accessed through the Vercel API using the Supabase service-role key.
-- Keep the public Data API closed: RLS is enabled below and no anon/authenticated
-- policies are created.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null check (price >= 0),
  image_url text,
  category text not null,
  affiliate_platform text not null,
  affiliate_url text not null,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  click_count integer not null default 0 check (click_count >= 0)
);

create table if not exists public.click_logs (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  clicked_at timestamp with time zone not null default now(),
  referrer_source text
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  salt text not null
);

create index if not exists products_active_created_at_idx
  on public.products (is_active, created_at desc);
create index if not exists products_category_active_idx
  on public.products (category, is_active);
create index if not exists products_featured_active_idx
  on public.products (is_featured, is_active);
create index if not exists click_logs_product_id_idx
  on public.click_logs (product_id);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.click_logs enable row level security;
alter table public.admin_users enable row level security;

insert into public.categories (name, slug, icon)
values
  ('Kecantikan', 'kecantikan', 'Sparkles'),
  ('Fashion', 'fashion', 'Shirt'),
  ('Gadget', 'gadget', 'Smartphone'),
  ('Rumah Tangga', 'rumah-tangga', 'House')
on conflict (slug) do nothing;
